services:
  - type: web
    name: exam-management-system
    env: docker
    branch: main
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-database-username
      - key: DB_PASS
        value: your-database-password
      - key: DB_NAME
        value: your-database-name
    buildCommand: ""
    startCommand: ""
